version: "3"
services:
  bitcoincore:
    build: ../../packages/nodechain-bitcoin-core
    image: bitcoincore
    command: -rpcuser=swapper
      -rpcpassword=swapper
      -server=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=bitcoincore
      -txindex=1
      -rpcport=8332
      -zmqpubhashblock=tcp://0.0.0.0:28332
    volumes:
      - ${BLOCKCHAIN_PATH}/bitcoincode:/home/bitcoin/.bitcoin

  electrs:
    build: ../../packages/nodechain-electrs
    image: electrs
    command: -v --timestamp
    depends_on:
      - bitcoincore
    environment:
      DAEMON_RPC_URL: bitcoincore:8332
      ELECTRUM_RPC_URL: 0.0.0.0:50001
    volumes:
      - ${BLOCKCHAIN_PATH}/electrs:/build/.electrs
      - ${BLOCKCHAIN_PATH}/bitcoincode:/home/bitcoin/.bitcoin

  electrum:
    build: ../../packages/nodechain-electrum
    image: electrum

networks:
  default:
    external:
      name: nodechain-network