version: "3"
services:
  bitcoincore:
    build: ../../packages/nodechain-bitcoin-core
    image: bitcoincore
    command: -rpcuser=swapper
      -rpcpassword=swapper
      -server=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=bitcoincore
      -txindex=1
      -rpcport=8332
      -zmqpubhashblock=tcp://0.0.0.0:28332
    volumes:
      - ${BLOCKCHAIN_PATH}/bitcoincode:/home/bitcoin/.bitcoin

  electrs:
    build: ../../packages/nodechain-electrs
    image: electrs
    command: -v --timestamp
    depends_on:
      - bitcoincore
    environment:
      DAEMON_RPC_URL: bitcoincore:8332
      ELECTRUM_RPC_URL: localhost:50001
    volumes:
      - ${BLOCKCHAIN_PATH}/electrs:/build/.electrs

  electrum:
    build: ../../packages/nodechain-electrum
    image: electrum

  connector:
    build: ../../Connector
    environment:
      COIN: BTC
      STAGE: ${STAGE}
      PORT: ${PORT}
    image: connector

  nginx:
    image: nginx
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
      - ${CERT_PATH}:/etc/nginx/certs
    ports:
      - ${PORT}:80
      - ${SSL_PORT}:443
