version: "3"
services:
  monerod:
    build: ../../packages/nodechain-monerod
    image: monerod
    command: --p2p-bind-ip=0.0.0.0 --p2p-bind-port=18080 --rpc-bind-ip=0.0.0.0 --rpc-bind-port=18081 --non-interactive --confirm-external-bind
    volumes:
      - ${BLOCKCHAIN_PATH}/bitmonero:/home/monero/.bitmonero
    user: "${UID}:${GID}"

networks:
  default:
    external:
      name: nodechain-network