version: 2
jobs:
  ethtest:
    machine:
      image: ubuntu-2004:202201-02
      docker_layer_caching: true
    environment:
      NETWORK: regtest
      PORT: 80
      SSL_PORT: 443
      NGINX_CONFIG_PATH: ../../nginx/nginx.conf
      CERT_PATH: /etc/ssl/certs
      BLOCKCHAIN_PATH: ./blockchain/
      COMPOSE_DOCKER_CLI_BUILD: 0
      DOCKER_BUILDKIT: 0
    steps:
      - checkout
      - run: 
          name: Create virtual environment
          command: |
            python3 -m venv venv/
            source venv/bin/activate
            pip3 install -r Connector/requirements.txt
            pip3 install -r scripts/requirements.txt
      - run: 
          name: Check Lint
          command: |
            source venv/bin/activate
            flake8 --statistics
      - run: 
          name: Deploy ETH regtest nodes
          command: |
            docker-compose -f Connector/tests/docker-compose/eth.yml -p eth_regtest_api up -d
      - run:
          name: Add ethereumgo to /etc/hosts
          command: |
            echo "127.0.0.1 ethereumgo" | sudo tee -a /etc/hosts
            cat /etc/hosts
      - run:
          name: Allow access to ports
          command: |
            sleep 5 && nc -vz localhost 8545
      - run:
          name: Run ETH Connector tests
          command: |
            source venv/bin/activate
            cd Connector && python -m pytest -c tests/eth/pytest_eth.ini -s --cov=eth/ tests/eth
  btctest:
    machine:
      image: ubuntu-2004:202201-02
      docker_layer_caching: true
    environment:
      NETWORK: regtest
      PORT: 80
      SSL_PORT: 443
      NGINX_CONFIG_PATH: ../../nginx/nginx.conf
      CERT_PATH: /etc/ssl/certs
      BLOCKCHAIN_PATH: ./blockchain/
      COMPOSE_DOCKER_CLI_BUILD: 0
      DOCKER_BUILDKIT: 0
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: |
            python3 -m venv venv/
            source venv/bin/activate
            pip3 install -r Connector/requirements.txt
            pip3 install -r scripts/requirements.txt
      - run: 
          name: Check Lint
          command: |
            source venv/bin/activate
            flake8 --statistics
      - run: 
          name: Build docker compose images
          command: |
            docker-compose -f Connector/tests/docker-compose/btc.yml -p btc_regtest_api build --no-rm
          no_output_timeout: 1h
      - run: 
          name: Deploy BTC regtest node
          command: |
            docker-compose -f Connector/tests/docker-compose/btc.yml -p btc_regtest_api up -d
      - run:
          name: Add electrum and bitcoincore to /etc/hosts
          command: |
            echo "127.0.0.1 electrum" | sudo tee -a /etc/hosts
            echo "127.0.0.1 bitcoincore" | sudo tee -a /etc/hosts
            cat /etc/hosts
      - run: 
          name: Allow access to ports
          command: |
            sleep 5 && nc -vz localhost 8332
            sleep 5 && nc -vz localhost 28332
            #sleep 5 && nc -vz localhost 3000
      - run:
          name: BitcoinCore set up
          command: |
            docker exec -it btc_regtest_api_bitcoincore_1 bash -c "rm -rf /home/bitcoin/.bitcoin/regtest/wallets/*"
      - run:
          name: Run BTC tests
          command: |
            source venv/bin/activate
            cd Connector && python -m pytest -c tests/btc/pytest_btc.ini -s --cov=btc/ tests/btc
workflows:
  version: 2
  tests:
    jobs:
      - btctest
      - ethtest
