version: "3"
services:
  # ethereumgo:
  #   image: ethereum/client-go:latest
  #   command: --http --http.addr=ethereumgo --ropsten --cache=1024 --http.port=8545 --syncmode=full --gcmode=archive --ws --ws.addr=ethereumgo --ws.port=8546 --ws.origins=connector
  #   volumes:
  #     - ${BLOCKCHAIN_PATH}/ethereumgo:/root/.ethereum

  ethereumgo:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command:
      -p=8545 -h=0.0.0.0 -m="piece effort bind that embrace enrich remind powder sudden patient legend group"
    volumes:
      - ${BLOCKCHAIN_PATH}/ethereumgo:/root/.ethereum

  connector:
    build: ../Connector
    environment:
      COIN: ETHTESTNET
      STAGE: ${STAGE}
      PORT: ${PORT}
    restart: on-failure
    depends_on:
      - ethereumgo
    links: 
      - ethereumgo
    image: connector

  nginx:
    image: nginx
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
      - ${CERT_PATH}:/etc/nginx/certs
    ports:
      - ${PORT}:80
      - ${SSL_PORT}:443